boostan/boostan/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from .settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('user/', include('member.urls', namespace='members')),
    path('requests/', include('request_manager.urls', namespace='request_manager')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

boostan/member/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import StudentLoginView, RegisterView, LogoutView
from boostan.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'members'

urlpatterns = [
    path('login/', StudentLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

boostan/member/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User


def score_validator(score):
    if int(score) < 0 or int(score) > 20:
        raise ValidationError('نمره باید بین 0 تا 20 باشد.')
    return score


class Member(models.Model):
    positions = (
        ('student', 'student'),
        ('employee', 'employee'),
        ('teacher', 'teacher'),
        ('personnel', 'personnel'),
        ('admin', 'admin')
    )

    user_profile = models.OneToOneField(User, on_delete=models.CASCADE)
    national_code = models.CharField(max_length=10, unique=True)
    profile_picture = models.ImageField(upload_to='member_pictures', default='member_pictures/default.jpeg')
    position = models.CharField(max_length=10, choices=positions, default='personnel')

    class Meta:
        db_table = 'members'
        verbose_name = 'Member'
        verbose_name_plural = 'Members'

    def __str__(self):
        return self.user_profile.username + " " + self.position


class Student(models.Model):
    member_profile = models.OneToOneField(Member, on_delete=models.CASCADE)
    department = models.CharField(max_length=10)
    passed_terms = models.IntegerField(default=0)

    class Meta:
        db_table = 'students'
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

    def __str__(self):
        return  str(self.member_profile.user_profile)


class Teacher(models.Model):
    member_profile = models.OneToOneField(Member, on_delete=models.CASCADE)
    department = models.CharField(max_length=10)
    course_numbers = models.IntegerField(default=0)
    personnel_code = models.CharField(max_length=10)

    class Meta:
        db_table = 'teachers'
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'

    def __str__(self):
        return str(self.member_profile.user_profile.first_name) + " " + str(self.member_profile.user_profile.last_name)


class Personnel(models.Model):
    member_profile = models.OneToOneField(Member, on_delete=models.CASCADE)
    role = models.CharField(max_length=30)

    class Meta:
        db_table = 'personnel'
        verbose_name = 'Personnel'
        verbose_name_plural = 'Personnel'

    def __str__(self):
        return "personnel-" + str(self.member_profile.national_code)


class Course(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=50)
    students = models.ManyToManyField(Student, related_name='courses')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        db_table = 'courses'
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'

    def __str__(self):
        return self.name


class Score(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    score = models.IntegerField(default=0, validators=[score_validator,])

    class Meta:
        db_table = 'scores'
        verbose_name = 'Score'
        verbose_name_plural = 'Scores'

boostan/member/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, authenticate, logout


class StudentLoginView(View):
    http_method_names = ['get', 'post']
    template_name = 'login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home')
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')

        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        if False in [username, password]:
            return render(request, self.template_name, {'error': 'لطفا هر دو مورد را وارد کنید.'})

        user = authenticate(username=username, password=password)

        if user is None or not user.is_active:
            return render(request, self.template_name, {'error': 'نام کاربری یا رمز عبور اشتباه است.'})


        try:
            login(request, user)
            return redirect('home')
        except:
            return render(request, self.template_name, {'error': 'خطایی رخ داد.'})


class RegisterView(View):
    http_method_names = ['get', 'post']
    template_name = 'register.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home')
        return render(request, self.template_name)

    def post(self, request):
        pass


class LogoutView(View):
    http_method_names = ['get', ]

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('home')
        logout(request)
        return redirect('home')

boostan/member/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ورود به سایت</title>
    <link rel="stylesheet" href="{% static 'css/login_style.css' %}">
</head>
<body>
    <div class="container">
            <h1 class="container_title">
                سامانه جهنم
            </h1>

        <div>
            <form class="login_form" action="{% url 'members:login' %}" method="post">
                {% csrf_token %}
                <label class="label" for="username">نام کاربری:</label>
                <input type="text" id="username" name="username">

                <label class="label" for="password">رمز عبور:</label>
                <input type="password" id="password" name="password">

                <input type="submit" value="ورود" id="btn_submit">
            </form>
            <div class="helper">
                <h2 class="error">{{ error }}</h2>
                <h4><a class="links" href="{% url 'members:register' %}">ایجاد حساب جدید</a></h4>
                <h4><a class="links" href="#">رمز عبور خود را فراموش کرده ام</a></h4>
{#                <h4><a href="" class="links">بخش اساتید</a></h4>#}
            </div>
        </div>
    </div>
</body>
</html>

boostan/member/templates/register.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ایجاد حساب جدید</title>
    <link rel="stylesheet" href="style/css/login_style.css">
</head>
<body>
    <div class="container">
            <h1 class="container_title">
                سامانه جهنم
            </h1>

        <div>
            <form class="login_form" action="">
                <label class="label" for="username">یک نام کاربری انتخاب کنید:</label>
                <input type="text" id="username">

                <label class="label" for="email">ایمیل:</label>
                <input type="email" id="email">

                <label class="label" for="password" class="label">رمز عبور:</label>
                <input type="password" id="password">

                <label class="label" for="password" class="label">تکرار رمز عبور:</label>
                <input type="password" id="password">

                <input type="submit" value="login" id="btn_submit">
            </form>
            <div class="helper">
                <h4><a class="links" href="login.html">من یک حساب دارم</a></h4>
                <!-- <h4><a class="links" href="">رمز عبور خود را فراموش کرده ام</a></h4> -->
            </div>
        </div>
    </div>
</body>
</html>