boostan/boostan/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from .settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('user/', include('member.urls', namespace='members')),
    path('requests/', include('request_manager.urls', namespace='request_manager')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

boostan/member/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import StudentLoginView, RegisterView, LogoutView
from boostan.settings import MEDIA_ROOT, MEDIA_URL

app_name = 'members'

urlpatterns = [
    path('login/', StudentLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

boostan/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>سامانه بوستان</title>
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/student_profile_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/admin_all_style.css' %}">
    <script src="{% static 'js/jQuery.js' %}"></script>

</head>
<body>
<div class="title">
    دانشگاه ... - سامانه جهنم
</div>

<div class="main_container">
    <aside>
        <div class="side_menu">
            <ul id="sideul">

            </ul>
        </div>
    </aside>

    <div class="side_left">

        <header class="header">
            <div class="header__menu">
                <ul>
                    <li>
                        {% if user and user.is_authenticated %}
                            <span>{{ user.first_name }} {{ user.last_name }} - {{ role }}</span>
                        {% else %}
                            <span>خطا در نام کاربری</span>
                        {% endif %}
                    </li>
                    <li><a href="{% url 'members:logout' %}">خروج</a></li>
                </ul>
            </div>

            <!-- <h4>نام کاربری</h4>
            <h4><a href="login.html">خروج</a></h4> -->
            <img class="profile_picture" src="{{ member.profile_picture.url }}" alt="عکس پروفایل">
        </header>

        <div class="sub_menu">
            <ul>
                <li></li>
            </ul>
        </div>

        <div id="display_content">

        </div>
    </div>
</div>
<script src="{% static 'js/menu_items.js' %}"></script>
<script src="{% static 'js/menu_functions.js' %}"></script>
</body>
</html>